language: python
python:
  - "2.7"
  - "3.3"
# command to run tests
script: nosetests
# Ensure dependencies are installed
install:
  - pip install .

# Enable new Travis stack, should speed up builds
sudo: false
